### ISSUE TITLE
Introducción al sistema ÁGORA

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#114]
Asimilar el funcionamiento general del sistema así como de su flujo y actividades necesarias por desarrollar, de acuerdo a las siguientes actividades:

- [x] Revisión e instalación de repositorios (Crud, Mid y Cliente).
- [x] Revisión de documentación.
- [x] Análisis de requerimientos.

**Criterios de aceptación**

1. Registrar el estado actual en el que se recibe el sistema (Formato propio).
2. Registrar inquietudes respecto a los requerimientos analizados.

**Comment by Yaov05** [comment]
Surgió un problema al momento de realizar la migración de la base de datos, que impedía ejecutar todos los scripts

![Error_script_crear_esquema_evaluacion_up](https://user-images.githubusercontent.com/42217637/126581377-c5b79d61-2e62-4e12-bf04-32d472ee7cbd.PNG)

Se intentó solucionar el error, sin éxito, por lo que, para ejecutar el CRUD de manera local, se ejecutaron las sentencias de los scripts en un Query en PgAdmin, con el fin de crear la base de datos.

**Comment by Yaov05** [comment]
Se corre el CRUD en local, en el puerto 8089, y se prueba un ENDPOINT para verificar el funcionamiento.

![get_clasificacion_1](https://user-images.githubusercontent.com/42217637/126582016-74a7189c-b746-4934-8602-d9db9778f4e9.PNG)

![get_clasificacion_2](https://user-images.githubusercontent.com/42217637/126582161-6d0ecaf1-1a94-453c-8dcc-08cded85db57.PNG)

**Comment by Yaov05** [comment]
Se ejecuta el módulo Evaluacion_mid de manera local, apuntando a la dirección de la API administrativa_amazon_api y se hace la prueba de /filtroContrato con valores arbitrarios.

![GetJsonTestObtenerContratosWeb](https://user-images.githubusercontent.com/42217637/126908135-fceb109a-5c8c-4694-bea2-07c8fed68a35.PNG)

En la consola, se puede ver que el error puede darse debido a que está recibiendo valores nulos, ya que actualmente no se cuenta con VPN, lo que impide la conexión.

![GetJsonTestObtenerContratosConsole](https://user-images.githubusercontent.com/42217637/126908316-dd100059-aa75-4b02-88a2-710cf3ccf786.PNG)

**Comment by Yaov05** [comment]
De igual manera con el módulo Evaluacion_Cliente, no es posible validar el estado del sistema por ahora, sin acceso a la VPN, ya que no logra obtener correctamente los valores del backend y genera un error relacionado con la autorización.

![BackendReturnedUndefined](https://user-images.githubusercontent.com/42217637/126926869-86728dce-db59-4928-a0ba-c6cff35057d6.PNG)

**Comment by Yaov05** [comment]
Se realiza la revisión de manera detallada de las de la documentación disponible en la carpeta de drive nombrada PROYECTO ÁGORA, 

https://drive.google.com/drive/u/2/folders/1o5ijcCnhLDS37wL_ExgJyig7xXGV7ClC

correspondiente a las siguientes subcarpetas:

- [x] PLANEACIÓN
- [x] INICIO
- [x] EJECUCIÓN
- [x] CIERRE
- [x] INFORMACIÓN ADICIONAL

Esto con el fin de lograr la apropiación de las generalidades del sistema.

**Comment by Yaov05** [comment]
Al correr la API Evaluacion_mid, genera un error al momento de obtener datos filtrados de un proveedor

![BeegoAppError1](https://user-images.githubusercontent.com/42217637/127248222-5427f7d0-6d4f-41d6-8329-fec38061a30f.PNG)

![BeegoAppError2](https://user-images.githubusercontent.com/42217637/127248248-9d5de8df-4f98-4da9-b2ef-cbe3fdf3b6bc.PNG)

Dirección que se da a las variables de entorno:

ADMIN_AMAZON_API_URL = http://pruebasapi.intranetoas.udistrital.edu.co:8104/
EVALUACION_CRUD_URL = http://pruebasapi.intranetoas.udistrital.edu.co:8506/
ADMIN_AMAZON_JBPM_URL = http://jbpm.udistritaloas.edu.co:8280/services/

**Comment by Yaov05** [comment]
Para la parte de los requerimientos, se tiene que son los correspondientes a las siguientes actividades

1. Validar en que estado están ambos módulos.
2. Realizar los ajustes pertinentes.
3. Desplegar.
4. Entregar al usuario.

Con las siguientes cosas a resaltar

1. Para el primer punto, se creó un issue para realizar el diagnóstico del sistema para los módulos especificados.

2. Los ajustes pertinentes dependen del diagnóstico del sistema y de los requerimientos específicos dados por el usuario. Estos últimos no se encuentran documentados en ninguna parte de la documentación del sistema, por lo que ha sido difícil listar puntualmente lo que se requiere para cada módulo y para cada rol. Se ha recurrido a revisar las grabaciones de las reuniones de la fase anterior para tener una idea mucho más clara de los ajustes que faltan (basado en la última reunión de revisión de ajustes finales). Sin embargo estos pueden no ser todos lo ajustes necesarios. Estos serán listados en el issue correspondiente al diagnóstico del sistema.


Las única duda relacionada con los requerimientos es, si la información detallada acerca del despliegue será proporcionada en su momento o es necesario conocer ese proceso desde un principio.
