### ISSUE TITLE
Propuesta del plan de trabajo (Módulo de evaluación y de certificación)

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#116]
Proponer el plan de trabajo correspondiente a la optimización de los módulos:

- Evaluación de proveedores.
- Certificación de novedades contractuales.

**Nota**:
Se debe tomar en consideración la validación del estado actual de los módulos, la revisión de tareas realizadas (Issues) y las actividades faltantes para realizar el despliegue y la entrega al usuario de los mimos.
 
De igual forma, se debe asignar prioridad y un estimado de tiempo a cada item.

**Criterios de aceptación**

- [x] Documento con la propuesta de trabajo realizada (Formato del documento libre).

**Comment by Yaov05** [comment]
Tras realizar la reunión con el gerente general del proyecto, se tuvo en cuenta que el sistema se encuentra parcialmente desplegado en producción, por parte del módulo de evaluación de proveedores, mientras que no es así por parte del módulo de certificaciones. A partir de esto, se realiza y se adjunta la propuesta de plan de trabajo.

[Propuesta de plan de trabajo.pdf](https://github.com/udistrital/evaluacion_cliente/files/6920283/Propuesta.de.plan.de.trabajo.pdf)

**Comment by a52290451** [comment]
Se valida y aprueba plan de trabajo propuesto.
