### ISSUE TITLE
Diagnostico del sistema para los módulos de evaluación y certificación

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#117]
Se debe realizar el diagnostico del sistema, con base en el [ultimo despliegue realizado](https://github.com/udistrital/evaluacion_cliente/issues/86) y la documentación relacionada (Issues y archivos en drive).

Material de apoyo
1. [Issue con documento para guía de levantamiento del diagnostico y tareas faltantes](https://github.com/udistrital/resoluciones_cliente/issues/68).
2. [Documento 2 para guía de revisión del estado actual del sistema](https://drive.google.com/file/d/1rtS32hsgk_66Q-TPm6wfzk3YkWzV2UJ2/view).

**Criterios de aceptación**

- [x] Documento en donde se especifique el estado en el cual se recibe el sistema, la validación de tareas realizadas en fases anteriores y las que faltan por realizar para desplegar el sistema.

**Comment by Yaov05** [comment]
Se crea el documento y se comienza a trabajar en él, evidenciando el estado actual del sistema. (Este diagnóstico ha tenido un retraso debido a que no se ha recibido la VPN a día de hoy, por lo que no se puede realizar pruebas funcionales para la validación)

Las pruebas funcionales documentadas en las carpetas de Drive son algo generales, por lo que se pretende incluir información más específica relacionada con algunas recomendaciones dadas por la jefe, el gerente general del proyecto, y el usuario en reuniones de la fase anterior. Entre estas pueden encontrarse cosas como:

-Permisos dependientes del rol, sobre todo para el módulo de certificaciones (Contratistas y Proveedores).
-Detalles que se den al momento de listar contratos (que se haga el filtro de la manera correcta, por ejemplo).
-Validaciones en los campos de texto para restringir la información que puede digitar un usuario.
-Entre otras.

En cuanto se tenga acceso a la VPN, se podrá continuar con el desarrollo de este diagnóstico de manera más detallada y se adjuntará el documento con el estado del sistema y las tareas realizadas y por realizar. Esto también dará paso para realizar el plan de trabajo.

**Comment by Yaov05** [comment]
El cliente presenta un problema al momento de realizar la petición a la API MID para filtrar los proveedores usando el documento del proveedor y el del supervisor.

![ErrorSupID](https://user-images.githubusercontent.com/42217637/127782865-a0040b20-91c5-48ce-b687-977140967933.PNG)

Se rastrea el error corriendo la API Evaluacion_mid de manera local. Funciona correctamente al usar cero para el ID del supervisor

![PruebaProveedor1](https://user-images.githubusercontent.com/42217637/127783186-cb22b6ee-5573-472b-bd08-08b737e7bf17.PNG)

Se detecta que el error es al momento de apuntar a la dirección administrativa_amazon_jbpm_url, es decir, cuando el ID del supervisor es distinto de cero

![ErrorProveedor](https://user-images.githubusercontent.com/42217637/127783242-814b66e9-f7e4-4709-8a61-8882bb3f72c1.PNG)

Se prueba realizar la petición directamente usando PostMan

![PruebaJBPM1](https://user-images.githubusercontent.com/42217637/127783283-5d62d4b7-40f4-4b49-b279-ddd0608b3e7d.PNG)

Posiblemente el problema es de administrativa_amazon_jbpm.

Se documenta esta información en el diagnóstico.

**Comment by Yaov05** [comment]
Se adjunta el diagnóstico del sistema para los módulos Evaluaciones y certificaciones.

[Diagnóstico y validación de módulos Evaluaciones y Certificaciones.docx.pdf](https://github.com/udistrital/evaluacion_cliente/files/6917171/Diagnostico.y.validacion.de.modulos.Evaluaciones.y.Certificaciones.docx.pdf)

**Comment by a52290451** [comment]
Se tiene conocimiento del problema indicado. Se tomaran las acciones pertinentes para solucionar dicho problema.

**Comment by a52290451** [comment]
Se soluciona problema notificado con JBPM.
