### ISSUE TITLE
Pruebas funcionales y de usabilidad.

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#118]
Se debe realizar la planeación y ejecución de pruebas funcionales y de usabilidad relacionadas con la optimización de los módulos de evaluaciones y certificaciones.

**Criterio de aceptación**

- [x] Documento que registre las pruebas funcionales y de usabilidad realizadas.

**Nota**: utilizar el [formato](https://docs.google.com/spreadsheets/d/1oymdKw9XVShKKk71AWzqUjPW-N26OdlRR_IB34X8Acs/edit#gid=481118634) dispuesto para la aplicación de este tipo de pruebas.

**Comment by Yaov05** [comment]
Para realizar las pruebas funcionales se cambia la dirección de JBPM por http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/administrativa_pruebas/dependencias_sic/ en la API Evaluacion_mid, por lo que se modifica el código del cliente para realizar peticiones a la API corriendo en local.

Se genera un error al momento de realizar el Request:

![ErrorHeaders](https://user-images.githubusercontent.com/42217637/128444334-ffcc160a-055c-4898-9ba9-9187def0190c.PNG)

**Comment by Yaov05** [comment]
Se adjunta el documento de Pruebas funcionales y de usabilidad.

[Pruebas Funcionales y de Usabilidad.xlsx](https://github.com/udistrital/evaluacion_cliente/files/6954496/Pruebas.Funcionales.y.de.Usabilidad.xlsx)

**Comment by Yaov05** [comment]
Se modifica el código de la API MID para que desde el cliente se pueda realizar una petición teniendo solamente el número de documento del proveedor y el año de vigencia del contrato.

![InkedCaptura1_LI](https://user-images.githubusercontent.com/42217637/128959156-5895f83d-bc87-41cf-801d-8f19198f44ad.jpg)

De esta manera se podrá ver sólo el contrato del año de vigencia seleccionado.

**Comment by Yaov05** [comment]
Se modifica la dirección de JBPM por http://api.intranetoas.udistrital.edu.co:8104/v1/ Para realizar las pruebas al traer información del contrato para el que se crea la certificación, en pruebas, toma correctamente la información y crea el certificado. 

![Captura2](https://user-images.githubusercontent.com/42217637/129124325-141f40d6-0f7f-4f07-afd1-a9c4826e6d82.PNG)

Sin embargo, la dirección mencionada no contiene información exacta de las actividades específicas del contrato ni las fechas de inicio y finalización, por lo que se tomó información distinta para hacer las pruebas.

**Comment by Yaov05** [comment]
Para las pruebas funcionales se usaron los siguientes EndPoints (principales):

Cliente

EVALUACIONCRUD_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/evaluacion_crud/v1/'
ADMINISTRIVA_AMAZON: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/administrativa_amazon_api/v1/'
ADMINISTRIVA_JBPM:'http://api.intranetoas.udistrital.edu.co:8104/v1/'
EVALUACIONMID_SERVICE: 'http://localhost:8080/v1/' (corriendo en local)

Mid

ADMIN_AMAZON_API_URL: 'http://pruebasapi.intranetoas.udistrital.edu.co:8104/'
ADMIN_AMAZON_JBPM_URL: 'http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/administrativa_pruebas/'
EVALUACION_CRUD_URL: 'http://pruebasapi.intranetoas.udistrital.edu.co:8506/'


Se adjunta nuevamente el documento de pruebas funcionales con el ítem faltante (módulo de evaluación de proveedores).

[Pruebas Funcionales y de Usabilidad.xlsx](https://github.com/udistrital/evaluacion_cliente/files/7034648/Pruebas.Funcionales.y.de.Usabilidad.xlsx)
