### ISSUE TITLE
Despliegue en preproducción.

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#119]
Realizar la gestión necesaria para desplegar los módulos de evaluación y certificaciones en ambiente de pruebas.

**Criterios de aceptación**

- [x] evaluacion_cliente.
- [x] evaluacion_mid.
- [x] evaluacion_crud.

**Comment by Yaov05** [comment]
Se crea una rama feature en el repositorio de Evaluacion_mid que incluye las funcionalidad de obtener las actividades del contrato y el ajuste de endpoints, 

![feature mid](https://user-images.githubusercontent.com/42217637/130790753-cbca2948-1d61-416a-bc1f-395baa4a395e.png)

De esta misma manera, se crea una rama en el cliente que incluye correción de errores en la generación de pdf's y ajuste en las peticiones realizadas.

Para realizar el despliegue en preproducción no fue necesario realizar ajustes en la API CRUD.

**Comment by Yaov05** [comment]
Se hace un pull request desde las ramas creadas en ambos repositorios hacia la rama develop de cada uno. Con esto, el líder técnico realiza el merge hacia la rama, y sugiere que se eliminen ambas ramas creadas anteriormente.

![pull request mid 1](https://user-images.githubusercontent.com/42217637/130791787-9d431ebd-850c-416c-86c5-5421e8e26590.png)

A partir de este punto, se realiza un pull request desde la rama develop hacia release en ambos repositorios, para que se realice el merge y finalizar el despliegue en ambiente de pruebas.

(Para la API MID fue necesario hacer una solicitud para cambiar las variables de entorno en aws en ambiente de pruebas).

**Comment by a52290451** [comment]
Se registra solicitud de actualización de variables de entorno para ambiente de pruebas en API MID:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=43102

**Comment by a52290451** [comment]
Se comprueba el correcto funcionamiento del sistema en ambiente de pruebas.
