### ISSUE TITLE
Despliegue en producción.

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#120]
Realizar la gestión necesaria para desplegar los módulos de evaluación y certificaciones en ambiente de producción.

**Criterios de aceptación**

- [x] evaluacion_cliente.
- [x] evaluacion_mid.
- [x] evaluacion_crud.

**Comment by Yaov05** [comment]
Para el despliegue en producción, fue necesario realizar un ajuste en las variables de entorno en ambiente de producción, principalmente para el API mid:

- Name: ADMIN_AMAZON_API_URL
Value: http://api.intranetoas.udistrital.edu.co:8104/
- Name: ADMIN_AMAZON_JBPM_URL
Value: http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/administrativa_produccion/
- Name: EVALUACION_CRUD_URL
Value: http://api.intranetoas.udistrital.edu.co:8506/

A partir de este punto, se presentó un problema con la base de datos de la que el API crud consulta información para las plantillas de evaluación de proveedores, por lo que fue necesario solicitar la actualización de las bases de datos en producción para las tablas necesarias.
