### ISSUE TITLE
Revisión y extensión de desarrollo para autenticación de documentos

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#121]
Se requiere revisar el desarrollo realizado en ÁGORA con soporte en NUXEO, con respecto a la autenticación única de documentos e identificar si es posible extender el alcance de esta funcionalidad a un servicio transversal en varios sistemas.

**Criterio de aceptación**

- [x] Reporte de la revisión y análisis para extensión de funcionalidad.

**Nota**

Tomar en consideración los siguientes issues:
1. [ISSUE #79](https://github.com/udistrital/evaluacion_cliente/issues/79).
2. [ISSUE #75](https://github.com/udistrital/evaluacion_cliente/issues/75).
3. [ISSUE #96](https://github.com/udistrital/evaluacion_cliente/issues/96).
4. [Tablero con issues en git](https://github.com/orgs/udistrital/projects/19?card_filter_query=label%3Acertificacion).

**Comment by criss201x** [comment]
Se realiza un análisis del flujo de autenticación documental para el modulo de certificaciones en el cliente de Agora con el fin de generalizar el proceso de autenticación documental electrónica para otros sistemas, el flujo de autenticación para este modulo viene dado entre varios sistemas y puede ser representado con la siguiente secuencia:

![FLUJO_AUTENTICACION](https://user-images.githubusercontent.com/57843585/129210599-8fa41fbb-8c70-45fb-b79e-22d7f8f0bc50.png)

**Observaciones** 

- Este flujo viene dado para documentos emitidos en el momento de su creación.
- La construcción y generación del archivo en pdf se da por medio de una librería js, en el lado del cliente.
- El proceso de generación del hash de un documento lo hace el sistema gestor documental Nuxeo.
- El sistema Urano también autentica los documentos de manera similar, Issue relacionado, [aquí](https://github.com/udistrital/evaluacion_cliente/issues/84).
