### ISSUE TITLE
Creación de Mock-Ups para Agregar links de redirección a Evaluaciones y Certificaciones

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#122]
Se requiere realizar la creación de Mock-ups para ÁGORA, a fin de señalar la ubicación en la que deberán estar los links necesarios para redirigir a la evaluación de proveedores desde el rol de supervisor en el modulo de Evaluaciones, y para redirigir a la consulta de certificados desde el rol de proveedor y supervisor en el módulo de Certificaciones.

**Criterio de aceptación**

- [x] Mock-ups en donde se evidencien los nuevos links señalados.

**Nota:** Tomar en consideración las siguientes imágenes

- Evaluaciones (rol de supervisor)

![image](https://user-images.githubusercontent.com/36229498/129973734-aee77c22-de59-4ff2-a67d-451fa421278b.png)

![image](https://user-images.githubusercontent.com/36229498/129973893-f6baf0d3-615e-415c-83b9-a1a26a483659.png)
 
- Certificaciones (rol de proveedor)

![image](https://user-images.githubusercontent.com/36229498/129973832-35e36de9-bfa1-413a-a27c-71820fe98161.png)

**Comment by Yaov05** [comment]
Agregar una pestaña para la gestión de evaluaciones, que incluya el enlace hacia el módulo

![Evaluacion1](https://user-images.githubusercontent.com/42217637/130147012-fc269951-4b2f-4d35-897d-9e1afa39306b.PNG)

![Evaluacion2](https://user-images.githubusercontent.com/42217637/130147118-29bcf57a-2862-4fb7-abe8-406064b7483e.PNG)

Al momento de dar en el enlace, se muestra al usuario un mensaje de alerta que le informe que debe iniciar sesión nuevamente en el módulo, tanto para evaluaciones (rol de supervisor) como para certificaciones (rol de proveedor)

![Evaluacion3](https://user-images.githubusercontent.com/42217637/130147260-5fabf2bc-159c-405e-8ab8-e71689e59c8f.PNG)

**Comment by Yaov05** [comment]
En la pestaña de gestión de certificados, añadir el enlace hacia el módulo de certificaciones.

![Certificaciones1](https://user-images.githubusercontent.com/42217637/130147372-993fc277-8243-4039-a4d1-c818c4ab6e69.PNG)

**Comment by a52290451** [comment]
Actividad completa
