### ISSUE TITLE
Ajuste de cliente - Certificaciones OS

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#129]
Se requiere corregir error en la generación de certificados para contratos de tipo OS en donde no se están tomando las fechas de inicio y fin correspondientes. Se debe bloquear la opción de generar estos certificados para el rol de jurídica y habilitar la opción para el rol de asistente de compras, permitiendo ingresar los valores de fechas de forma manual.

**Criterio de aceptación**

- [x] Corrección del error.

**Comment by Yaov05** [comment]
Se añaden dos campos únicamente en el formulario de certificaciones de cumplimiento, que permitan ingresar la fecha de inicio y finalización del contrato de forma manual
![AjusteClienteCertificacionesOS](https://user-images.githubusercontent.com/42217637/133815908-59379c02-15a7-4459-be24-0e131577277d.PNG)

**Comment by Yaov05** [comment]
Ya que se utilizan distintos componentes para la certificación CPS y OS, el usuario de jurídica visualiza un componente distinto al usuario de asistente de compras. Esto quiere decir que el usuario de jurídica solamente puede crear certificados de CPS.

![AjusteClienteCertificacionesCPS](https://user-images.githubusercontent.com/42217637/134221502-a5d5d56f-6e75-4139-bd04-06ba8fcc0b75.PNG)

El error queda corregido permitiendo crear certificados de ambos tipos dependiendo el usuario que accede.

**Comment by a52290451** [comment]
Se valida corrección del error
