### ISSUE TITLE
Validar implementación del módulo de autenticación con Google en otros sistemas.

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#131]
Validar la implementación del módulo de autenticación con Google y autenticación hibrida en otros sistemas (Alternancia, Pólux y Titan), según sea el caso.

**Criterio de aceptación**

- [x] Análisis de las tareas a realizar (lista) para la implementación del módulo en el sistema evaluaciones.

**Material de apoyo**

- [Autenticación hibrida google-wso2 para clientes en angularjs](https://github.com/udistrital/core_module_angularjs/issues/6)
- [Autenticación google en TITAN](https://github.com/udistrital/titan_cliente/commit/4f7b4c80bc62f44f5b72147c7b5ba6e1c453cf3c)

**Comment by Yaov05** [comment]
Se sugiere que para evaluacion_cliente, en entorno de pruebas se pueda realizar la autenticación de manera híbrida (Google y WSO2) y en producción únicamente con Google.

Las tareas se realizarán en este orden:

-Desarrollar autenticación con Google para producción.
-Implementar la autenticación de manera simultánea con la actual.
-Desarrollar autenticación Híbrida para preproducción

Para implementar la autenticación con Google se va a realizar basado en WebComponent. Se tiene en cuenta el siguiente enlace que es un commit del cliente del sistema SGA, el cual se toma como base:

https://github.com/udistrital/sga_cliente/commit/c50b63e7b9b69fdbd1d197e995e34a63ae2d998d
