### ISSUE TITLE
Implementación del módulo en sistema de evaluaciones (mid y cliente).

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#132]
Realizar el desarrollo necesario en el API MID y cliente de evaluaciones con relación a la integración del módulo de autenticación con google.

**Criterio de aceptación**

- [x] Commits en ramas features con desarrollo realizado.

**Comment by Yaov05** [comment]
Se comienza a desarrollar la autenticación con Google en una nueva rama feature con el nombre 'feat--authService-WebComponent'.

En cuanto al orden en el que se desarrolla la autenticación, se opta por hacer primero la autenticación híbrida, añadiendo una opción para autenticar con Google al formulario ya existente de autenticación con WSO2

![Auth](https://user-images.githubusercontent.com/42217637/136386010-f41663f6-3037-491c-831b-8b9cd190f846.PNG)

A partir de este punto se comienza a desarrollar la autenticación únicamente con Google, para lo que se creará una rama nueva.

**Comment by Yaov05** [comment]
Para el módulo de autenticación fue necesario un componente con información del sistema que redireccione al formulario para diligenciar las credenciales de WSO2 o Google en el caso dado
![AGORA](https://user-images.githubusercontent.com/42217637/138696737-1b0d3adf-215c-4223-a42a-ba0dde9e01d7.PNG)
.

**Comment by Yaov05** [comment]
Commit: "Se implementa autenticación con google basada en WebComponent"
Link: https://github.com/udistrital/evaluacion_cliente/commit/579d870c044efa5fc5a2e709bd2b400d1cc9ba0e
