### ISSUE TITLE
Pruebas funcionales y de usabilidad

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#133]
Se debe realizar la planeación y ejecución de pruebas funcionales y de usabilidad relacionadas con la integración del módulo de autenticación con Google.

**Criterio de aceptación**

- [x] Documento que registre las pruebas funcionales y de usabilidad realizadas.

**Nota:** utilizar el [formato](https://docs.google.com/spreadsheets/d/1oymdKw9XVShKKk71AWzqUjPW-N26OdlRR_IB34X8Acs/edit?usp=sharing) dispuesto para la aplicación de este tipo de pruebas.

**Comment by a52290451** [comment]
Se deben solicitar pruebas funcionales a soporte.

**Comment by Yaov05** [comment]
Se indica que para las pruebas funcionales de este módulo no es necesario solicitar las pruebas a soporte. Por lo tanto, se adjunta el documento con el registro de las pruebas y observaciones:

[Pruebas Funcionales y de Usabilidad - Autenticación.xlsx](https://github.com/udistrital/evaluacion_cliente/files/7464949/Pruebas.Funcionales.y.de.Usabilidad.-.Autenticacion.xlsx)
