### ISSUE TITLE
Corrección de plantillas utilizadas en el cliente - Modulo de certificaciones.

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#142]
Corregir plantilla codificada en el cliente, ajustándola de acuerdo a la [nueva plantilla](https://github.com/udistrital/evaluacion_cliente/issues/141). Tener en consideración el espacio reservado para la firma del supervisor.

**Criterio de aceptación**

- [x] Commit con cambios realizados.

**Comment by Yaov05** [comment]
En la certificación contractual, se actualizó completamente el formato de la misma, de acuerdo a los requerimientos de la Oficina Asesora Jurídica, este nuevo formato incluye otros cambios como:

- Modificar la manera en la que consulta novedades.
- Cambiar la firma digital del jefe de la Oficina Asesora Jurídica.

Link del commit con los cambios que contienen estas correcciones:
https://github.com/udistrital/evaluacion_cliente/commit/c89b047c291daf11562a53c77a1c3166b08a5acd

Se realiza un pull request para despliegue en ambiente de pruebas:
https://github.com/udistrital/evaluacion_cliente/pull/156
