### ISSUE TITLE
Ajustes asociados a la información mostrada en el certificado - Modulo de certificaciones.

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#143]
Se requiere corregir error en la generación de certificaciones de cumplimento, en donde no se muestra información asociada al contratista. Adicionalmente, se debe permitir tomar la decisión de mostrar o no en la certificación, la calificación realizada.

**Criterio de aceptación**

- [x] Commit con cambios realizados.

**Comment by Yaov05** [comment]
En la certificación de cumplimiento, no se mostraba información acerca del proveedor. También hace falta agregar un campo para la firma del supervisor en la certificación. Ambas cosas son corregidas.

Link del commit con los cambios que contienen estas correcciones:
https://github.com/udistrital/evaluacion_cliente/commit/c89b047c291daf11562a53c77a1c3166b08a5acd

Se realiza un pull request para despliegue en ambiente de pruebas:
https://github.com/udistrital/evaluacion_cliente/pull/156
