### ISSUE TITLE
Pruebas funcionales - Corrección de errores - Modulo de certificaciones.

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#144]
Se debe realizar la planeación y ejecución de pruebas funcionales y de usabilidad relacionadas con la corrección de errores en el modulo de certificaciones.

**Criterio de aceptación**

- [x] Documento que registre las pruebas funcionales y de usabilidad realizadas.

**Nota:** utilizar el [formato ](https://docs.google.com/spreadsheets/d/1oymdKw9XVShKKk71AWzqUjPW-N26OdlRR_IB34X8Acs/edit?usp=sharing) dispuesto para la aplicación de este tipo de pruebas.

**Comment by Yaov05** [comment]
Las pruebas funcionales se solicitaron a soporte de primer nivel. Se adjunta documento con el resultado de las pruebas:

[Resultado de pruebas.docx](https://github.com/udistrital/evaluacion_cliente/files/7670408/Resultado.de.pruebas.docx)

Se presentó un inconveniente con las novedades que se consultaban para la certificación, lo que fue registrado en el documento de las pruebas y posteriormente corregido.
