### ISSUE TITLE
Pruebas unitarias - Modulo de certificaciones

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#145]
Implementar pruebas unitarias y refactor si es necesario, relacionadas con el modulo de certificaciones.

**Criterios de aceptación**

- [x] Registro de pruebas unitarias desarrolladas, junto con los resultados obtenidos.

**Material de apoyo:**

Revisar esta [plantilla](https://docs.google.com/document/d/1Uuk4IQHjhwm-3rQWwsmZQ5uts6X3SCEJ8OpJEsvUHXU/edit) como guía para el desarrollo de pruebas unitarias, así como los lineamientos de la OAS asociados a las mimas.

**Comment by Yaov05** [comment]
Se realizan las pruebas unitarias de los archivos que contienen funciones encargadas de reunir información necesaria para el módulo de certificaciones.

[Pruebas Unitarias - Módulo de certificaciones.docx](https://github.com/udistrital/evaluacion_cliente/files/7670373/Pruebas.Unitarias.-.Modulo.de.certificaciones.docx)

Para la realización de estas pruebas fue necesario asignar algunos endpoints directamente en el código, de lo contrario generaba error porque no reconocía las variables de entorno.
