### ISSUE TITLE
Validación de funcionalidades

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#173]
Se requiere validar los siguientes casos en el módulo de evaluaciones y certificaciones de ÁGORA:

1. Funcionamiento estandar.
2. Validación de casos de certificación (se adjuntan casos).
3. Validar creacion de certificaciones por parte de juridica, seccion de compras y de contratistas.
4. Información de cps y las OS en certificaciones.

Link de certificados: https://drive.google.com/drive/folders/1K-x_Eqd0D7kXE_RVDsDehinaVyU1HmWO?usp=sharing

**Comment by Yaov05** [comment]
Se realiza la validación de casos y se halla un aparente error en los datos, se presenta en un caso en particular (contrato 1004 de 2021) en el que el valor del contrato de la certificación generada es distinto al del caso adjunto para el contrato, por lo que se procede a revisar el flujo de la información para hallar el por qué de esta discrepancia.

Valor del contrato de la certificación generada:
![image](https://user-images.githubusercontent.com/42217637/162030575-8d526dd4-1efc-4ae9-9cc7-dc6055141ce1.png)

Valor del contrato en el caso adjunto:
![image](https://user-images.githubusercontent.com/42217637/162030659-0fc4b084-3986-4996-a698-63121553f9ff.png)

**Comment by Yaov05** [comment]
A continuación se listan las diferentes funcionalidades con los roles que pueden acceder a estas:

Realizar Evaluación de proveedores:
-ORDENADOR_DEL_GASTO
-SUPERVISOR

Ver Evaluación realizada:
-ORDENADOR_DEL_GASTO
-SUPERVISOR

Crear Certificación de Cumplimiento:
-ORDENADOR_DEL_GASTO
-SUPERVISOR
-ASISTENTE_COMPRAS
-OPS

Crear Certificación Contractual:
-ORDENADOR_DEL_GASTO
-SUPERVISOR
-ASISTENTE_JURÍDICA
-CONTRATISTA

Ver y Descargar Certificaciones creadas:
-ORDENADOR_DEL_GASTO
-SUPERVISOR
-ASISTENTE_JURÍDICA
-ASISTENTE_COMPRAS
-CONTRATISTA
-OPS


Se adjuntan los usuarios de prueba de cada rol (el usuario y la contraseña son el mismo) :

-ORDENADOR_DEL_GASTO: pruebasoas1
-ASISTENTE_JURÍDICA: pruebasjuridica
-ASISTENTE_COMPRAS: pruebascompras

**Comment by a52290451** [comment]
Se requiere adjuntar los usuarios de prueba para cada rol señalado.
