### ISSUE TITLE
Desarrollo de Firma electrónica y campo de observaciones

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#174]
Se requiere implementar firma electrónica de certificaciones de cumplimiento mediante rubrica para la sección de compras y campo de observaciones para el módulo de evaluaciones.

**Criterios de aceptación**

- [x] Desarrollo de firma electrónica mediante rubrica.
- [x] Desarrollo de campo de observaciones en módulo de evaluaciones.
- [x] Desplieguen en ambiente de pruebas.
- [x] Pruebas funcionales.
- [x] Despliegue en ambiente de producción.

Nota: Se adjunta [rubrica](https://docs.google.com/document/d/137jOgmJdMiGKaNyvo0qpV47hGXZyHPDh/edit?usp=sharing&ouid=104124925692794756698&rtpof=true&sd=true) para firma electrónica de certificaciones de cumplimiento.

**Comment by Yaov05** [comment]
Para el desarrollo de la firma de nota que el jefe de la sección de compras no ha cambiado por lo que la firma ya está implementada. Se consulta si es necesario añadir las firmas de los encargados de elaborar y aprobar la certificación.
![image](https://user-images.githubusercontent.com/42217637/162028845-7ad481a8-a2db-4fcc-be1c-55ab421cfb72.png)

**Comment by Yaov05** [comment]
Se agrega un campo opcional al momento de realizar la certificación que permita agregar observaciones a la misma.

![image](https://user-images.githubusercontent.com/42217637/162029236-12ecfd89-4dcc-4b5c-83ec-ba0942c1334b.png)

En el documento se añade las observaciones al final

![image](https://user-images.githubusercontent.com/42217637/162029349-00aac2c3-8e5f-4d6b-899a-806b2a588f64.png)
