### ISSUE TITLE
Mockups para multiples evaluadores

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#175]
Realizar mockups para habilitar la opción de agregar multiples evaluadores en una evaluación, cuando un contrato tiene mas de un supervisor a cargo.

**Comment by Yaov05** [comment]
Se propone agregar campos para agregar los evaluadores o supervisores de un proveedor al final de la evaluación para ser agregados al documento en caso de que halla más de un supervisor.

![Untitled Diagram (3)](https://user-images.githubusercontent.com/42217637/164067847-1b5035b0-4d10-46d6-bb3b-cf063f650e2b.jpg)

Puede quedar el espacio para los evaluadores justo antes del puntaje total de la evaluación o justo después.

**Comment by Yaov05** [comment]
Al ser añadidos diferentes evaluadores estos pueden ser agregados al documento usando una tabla y dejando un espacio para colocar la firma de cada supervisor.

![Untitled Diagram (2)](https://user-images.githubusercontent.com/42217637/164068549-76678765-dc74-4bb4-9ce5-20c01478c371.jpg)

Esto puede ser añadido al documento usando la tabla o simplemente dejando un espacio junto al nombre del supervisor para colocar la firma.

**Comment by a52290451** [comment]
Se aprueban mockups presentados.
