### ISSUE TITLE
plantilla dinamica

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/evaluacion_cliente#18]
el modulo de plantilla dinámica tiene el fin de construir una plantilla con base en un json que esta recibirá.

el modulo debe de cumplir con los siguientes items 

- [x] el modulo debe ser llamado dentro del componente de realizar evaluación. 

- [x] el modulo debe ser llamado dentro del componente de ver evaluación. 

- [x] el modulo debe de mostrar los datos de los diferentes textos que provienen de la plantilla, esto basado en el mockup. 

- [x] el modulo debe de mostrar las opciones de cada select. 

- [x] el modulo tiene varios secciones, según la opción de cada select, este debe de calcular el valor total de la sección. 

- [x] se deben de sumar todos los totales de las secciones en un total de la evaluación. 

- [x] segun el puntaje total de la evaluación se debe ir mostrando la clasificación correspondiente creo que esto no esta en el mockup, pero puede ir justo al lado del valor total, esta clasificación son items que van en el json de la plantilla, se evaluara a que clasificación corresponde segun su puntaje) 

- [x] las secciones hijas tienen condiciones para aparecer o no según la opción escogida de la sección hermana anterior, esa validación debe realizarse y mostrar o ocultar las secciones que tengan dichas dependencias. 

- [x] la plantilla debe obtenerse de una petición del mid

- [x] en espera del cumplimiento al item anterior se realizara el issue #20 en el cual se construirá la base de la plantilla a ingresar. 

- [x] según el donde sea llamada debe de cambiar los select por label, es decir si es llamada desde el componente de realizar evaluación, alli mostrara select para las opciones, pero si es llamada desde el componente de ver evaluación, deberán de ser input.

---

***los datos a mostrar de las evaluaciones se tomaran en otra tarea distinta*** 

***cualquier novedad sobre eta tarea o cambios se registraran en los comentarios***

**Comment by grumysh** [comment]
Mockup: https://www.draw.io/#G1LR9DwzfaFSoEmWc4PWOIicGhS6XIxRrd
Json: https://anyfile-notepad.semaan.ca/app#edit/GoogleDrive/1jluk9uJ0W-b6dYunjDWCnIEoNcpvUSRJ

**Comment by grumysh** [comment]
Se crea la planilla con base en el json planteado por @BOTOOM: 
![image](https://user-images.githubusercontent.com/29903400/70829822-aa832500-1dbc-11ea-9060-85d516dbfd8a.png)

**Comment by BOTOOM** [comment]
este issue ha sido actualizado con diferentes ítems, por fa dale check a los que ya estén realizados
