### ISSUE TITLE
Documentación y entrega final

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#191]
Se requiere registrar la documentación generada de Evaluación (planeación, modelo de datos, historias de usuario, diagramas, modulos, funcionalidades, manuales de usuarios, videotutoriales, pruebas realizadas, etc) en la fase actual, junto con acta de aceptación de entregable debidamente diligenciada y firmada por las partes involucradas.

Nota: para el documento de entrega final, utilizar la siguiente plantilla:
[Plantilla - Diagnostico Final por sistema.docx](https://github.com/udistrital/novedades_cliente/files/9087643/Plantilla.-.Diagnostico.Final.por.sistema.docx)

**Comment by Yaov05** [comment]
Se adjunta el documento con la información requerida:
[Diagnostico Final sistema Evaluación.docx](https://github.com/udistrital/evaluacion_cliente/files/9124901/Diagnostico.Final.sistema.Evaluacion.docx)

**Comment by a52290451** [comment]
Se valida y aprueba documentación entregada
