### ISSUE TITLE
Conexión de evaluacion_cliente con gestor_documental_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#196]
De acuerdo con el [análisis](https://github.com/udistrital/autenticacion_mid/issues/58) realizado, se requiere implementar lógica para conectar el módulo de evaluaciones de AGORA con el API gestor_documental_mid. En este sentido, se debe tomar como referencia la implementación realizada en [cumplidos_cliente](https://github.com/udistrital/cumplidos_cliente/commit/2c5e9403739ca5135aa556f3039c02c9309700cc) realizando la creación de su servicio el los demas cambios requeridos.

**Criterios de aceptación**

- [x] Creación de rama Feat para nuevo desarrollo en evaluacion_cliente.
- [x] Desarrollo en local.
- [x] Pruebas en local.
- [x] Commit en rama feat. 
- [x] Pull request en rama Develop
- [x] Pull request en ambiente de pruebas: "rama release". - Requiere aprobación.
- [x] Pruebas funcionales.
- [x] Check-list para despliegue en ambiente de producción.
- [x] Pull request en ambiente de producción: "rama master". - Requiere aprobación.
- [x] Estabilización del API.

**Comment by a52290451** [comment]
Formato para registro de pruebas: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBpkXWOtAmxOqr9XyhpASZxQ?e=hXbKyL

**Comment by NeFaWaltPint** [comment]
## Local
Se hace testeo de conexión a gestor documental mid probando la descarga de documentos.
![Test conexion get](https://user-images.githubusercontent.com/31144689/223461918-7acb1974-0ec9-42d1-874b-8e09015c4893.jpg)
Respuesta a peticipon GET pasando UUID de documento exitosa, retorno de Status 200, y json con archivo pdf en base64.

## Pruebas
![Captura desde 2023-03-07 10-29-59](https://user-images.githubusercontent.com/31144689/223471399-84b47fe4-3a39-45c5-8ca9-3c990a55a98a.png)

**Comment by NeFaWaltPint** [comment]
## Documentación pruebas funcionales:

Doc con evidencia de pruebas en ambiente local y de pruebas.
https://docs.google.com/spreadsheets/d/1bwyZbr4sWctDu4nHqW3TRiU_LEeJVUZx/edit?usp=sharing&ouid=101099474609200829289&rtpof=true&sd=true
_(Alojado en drive, compartido para usuarios udistrital)_
