### ISSUE TITLE
Desarrollo de consulta y guardado de documentos con gestor_documental_mid para Certificaciones contractuales.

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#197]
De acuerdo con el [análisis](https://github.com/udistrital/autenticacion_mid/issues/58) realizado, se requiere implementar lógica para almacenar y consultar documentos asociados a certificaciones contractuales en nuxeo a través del API gestor_documental_mid.

**Criterios de aceptación**

- [x] Creación de rama Feat para nuevo desarrollo en evaluacion_cliente.
- [x] Desarrollo en local.
- [x] Pruebas en local.
- [x] Commit en rama feat. 
- [x] Pull request en rama Develop
- [x] Pull request en ambiente de pruebas: "rama release". - Requiere aprobación.
- [x] Pruebas funcionales.
- [x] Check-list para despliegue en ambiente de producción.
- [x] Pull request en ambiente de producción: "rama master". - Requiere aprobación.
- [x] Estabilización del API.

**Comment by a52290451** [comment]
Se adjunta formato de checklist para despliegue a producción:

[Formato.CheckList.docx](https://github.com/udistrital/evaluacion_cliente/files/10910895/Formato.CheckList.docx)

**Comment by NeFaWaltPint** [comment]
## Local 
Petición POST existosa de gestor documental mid al enviar uuid de documento, retornando uid e información relacionada a al carga del archivo. 
![Test post Contractual](https://user-images.githubusercontent.com/31144689/223729502-01ecc416-1676-4e25-b68e-f9a6629a1a42.jpg)
Petición GET exitosa a gestor documental pasando el UUID entregado en la respuesta de la petición post.
![Test get Contractual](https://user-images.githubusercontent.com/31144689/223729627-fdc6092b-93cd-4701-8c82-cd44e9e2c000.jpg)

## Pruebas
![Captura desde 2023-03-07 10-31-29](https://user-images.githubusercontent.com/31144689/223729736-85dcadc4-5ba3-47b0-aa06-a3c03e171c0c.png)

**Comment by NeFaWaltPint** [comment]
## Documentación pruebas funcionales:

Doc con evidencia de pruebas en ambiente local y de pruebas.
https://docs.google.com/spreadsheets/d/1bwyZbr4sWctDu4nHqW3TRiU_LEeJVUZx/edit?usp=sharing&ouid=101099474609200829289&rtpof=true&sd=true
_(Alojado en drive, compartido para usuarios udistrital)_
