### ISSUE TITLE
Desarrollo de consulta y guardado de documentos con gestor_documental_mid para Certificaciones de cumplimiento.

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#198]
De acuerdo con el [análisis](https://github.com/udistrital/autenticacion_mid/issues/58) realizado, se requiere implementar lógica para almacenar y consultar documentos asociados a certificaciones de cumplimiento en nuxeo a través del API gestor_documental_mid.

**Criterios de aceptación**

- [x] Creación de rama Feat para nuevo desarrollo en evaluacion_cliente.
- [x] Desarrollo en local.
- [x] Pruebas en local.
- [x] Commit en rama feat. 
- [x] Pull request en rama Develop
- [x] Pull request en ambiente de pruebas: "rama release". - Requiere aprobación.
- [x] Pruebas funcionales.
- [x] Check-list para despliegue en ambiente de producción.
- [x] Pull request en ambiente de producción: "rama master". - Requiere aprobación.
- [x] Estabilización del API.

**Comment by NeFaWaltPint** [comment]
## Local
Petición POST existosa de gestor documental mid al enviar uuid de documento, retornando uid e información relacionada a al carga del archivo.
![Test post cumplimiento](https://user-images.githubusercontent.com/31144689/223729993-dcaaed07-c3fd-4a93-a0d8-a4423d08d7c8.jpg)
Petición GET exitosa a gestor documental pasando el UUID entregado en la respuesta de la petición post.
![Test get cumplimiento](https://user-images.githubusercontent.com/31144689/223730086-050d443a-a2af-485e-a6a1-d7909f4838fc.jpg)

## Pruebas
![Captura desde 2023-03-07 10-33-17](https://user-images.githubusercontent.com/31144689/223730137-a4986de0-7953-4b76-b521-0de7dd22916b.png)

**Comment by NeFaWaltPint** [comment]
## Documentación pruebas funcionales:

Doc con evidencia de pruebas en ambiente local y de pruebas.
https://docs.google.com/spreadsheets/d/1bwyZbr4sWctDu4nHqW3TRiU_LEeJVUZx/edit?usp=sharing&ouid=101099474609200829289&rtpof=true&sd=true
_(Alojado en drive, compartido para usuarios udistrital)_
