### ISSUE TITLE
Desacoplar y eliminar conexión entre evaluacion_cliente y nuxeo_mid/nuxeo_api

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#200]
De acuerdo con el [análisis](https://github.com/udistrital/autenticacion_mid/issues/58) realizado, se requiere desacoplar y eliminar todo lo relacionado con conexiones directas entre evaluacion_cliente y nuxeo_mid o nuxeo_api.

**Criterios de aceptación**

- [x] Creación de rama Feat para nuevo desarrollo en evaluacion_cliente.
- [x] Desarrollo en local.
- [x] Pruebas en local.
- [x] Commit en rama feat. 
- [x] Pull request en rama Develop
- [x] Pull request en ambiente de pruebas: "rama release". - Requiere aprobación.
- [x] Pruebas funcionales.
- [x] Check-list para despliegue en ambiente de producción.
- [x] Pull request en ambiente de producción: "rama master". - Requiere aprobación.
- [x] Estabilización del API.

**Comment by NeFaWaltPint** [comment]
## Local
Petición GET exitosa a gestor documental pasando el UUID entregado en la respuesta de la petición post.
![Test get luego desacople nuxeo](https://user-images.githubusercontent.com/31144689/223730418-f5cc8fed-2d38-4066-a900-d9b948c3d4ac.png)

## Pruebas
![Captura desde 2023-03-07 10-36-25](https://user-images.githubusercontent.com/31144689/223730451-d37baf80-f722-49d5-88be-4c40a458eacc.png)

**Comment by NeFaWaltPint** [comment]
## Documentación de pruebas
Pruebas realizadas en evaluación cliente para issues: #196 #197 #198 #200
[Pruebas Funcionales - EVALUACION.xlsx](https://github.com/udistrital/evaluacion_cliente/files/10921214/Pruebas.Funcionales.-.EVALUACION.xlsx)

**Comment by NeFaWaltPint** [comment]
## CheckList para despliegue en producción

[Formato.CheckList.docx](https://github.com/udistrital/evaluacion_cliente/files/10921236/Formato.CheckList.docx)

**Comment by NeFaWaltPint** [comment]
## Documentación pruebas funcionales:

Doc con evidencia de pruebas en ambiente local y de pruebas.
https://docs.google.com/spreadsheets/d/1bwyZbr4sWctDu4nHqW3TRiU_LEeJVUZx/edit?usp=sharing&ouid=101099474609200829289&rtpof=true&sd=true
_(Alojado en drive, compartido para usuarios udistrital)_
