### ISSUE TITLE
Informe final de Cierre - CORE - 2022 - 2023

### ISSUE THREAD

**Issue by a52290451** [udistrital/evaluacion_cliente#219]
Se requiere realizar el informe final de cierre asociado a CORE, en el cual se indique:

1. El estado en el cual se entregan los sistemas modificados.
2. Las mejoras realizadas.
3. La deuda tecnica de las implementaciones.
4. Los errores conocidos.
5. Limitaciones.
6. Las tareas faltantes por realizar para salir a producción en los desarrollos.
7. Los usuarios de prueba activos en los sistemas con sus respectivos roles.
8. Videotutoriales y manuales de usuario.

Tomar como referencia el [informe de cierre final de NOVEDADES](https://github.com/udistrital/novedades_cliente/files/10724321/Diagnostico.Final.Novedades.1.docx).

**Comment by NeFaWaltPint** [comment]
Adjunto informe preliminar de cierre para revisión:

[Informe Final de Cierre.docx](https://github.com/udistrital/evaluacion_cliente/files/11052260/Informe.Final.de.Cierre.docx)

**Comment by NeFaWaltPint** [comment]
## Informe final de cierre

Informe documentando las mejoras, deudas, limitaciones y tareas para salir a producción.
https://docs.google.com/document/d/11CWcd5Ee4cfHLEhbgwawcTl_zSQU3-aL/edit?usp=sharing&ouid=101099474609200829289&rtpof=true&sd=true
_(Alojado en drive, compartido para usuarios udistrital)_
