### ISSUE TITLE
Inhabilitación de opciones de certificado de contratos

### ISSUE THREAD

**Issue by milo19980525** [udistrital/evaluacion_cliente#225]
Inhabilitar opciones asociadas a la generación de certificados de cumplimiento para los roles de contratista y asistente de jurídica.

**Especificaciones técnicas**

- Se requiere el ajuste de opciones habilitadas para generar un certificado de contrato a partir de la modificación de las encontradas en el cliente en producción mediante la aplicación de un hotfix.

**Sub Tareas**

- [x] Restringir la opción de OTROS para el rol de contratista y dejar por defecto el valor de "NO".
- [x] Ocultar la opción "novedades" para los roles de ordenador de gasto y asistente de jurídica y dejar por opción por defecto "sin novedades".

**Criterios de aceptación**

- [x] Se deben poder visualizar los cambio en el cliente de evaluación ambiente de producción.

**Requerimientos**

- Ninguno

**Dependencias**

- Ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Hotfix.
- [x] Pruebas en local.
- [x] PR a Master.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ludwinggsanchez** [comment]
Ajuste para el rol de **JURÍDICA**
![image](https://user-images.githubusercontent.com/35748918/235823320-f576435a-6a29-495a-97f7-4d5405182671.png)

**Comment by ludwinggsanchez** [comment]
Ajuste para rol **CONTRATISTA**

![image](https://user-images.githubusercontent.com/35748918/235823500-36e49c6f-5032-4a3e-b027-18298505fb6f.png)
