### ISSUE TITLE
Ajuste de novedades en el módulo de certificaciones

### ISSUE THREAD

**Issue by milo19980525** [udistrital/evaluacion_cliente#249]
Se requiere implementar el consumo de novedades CPS poscontractuales desde el api de novedades, en las certificaciones contractuales del módulo de evaluaciones.

**Especificaciones técnicas**

- El último desarrollo certificaciones contractuales se encuentra en master.
- El desarrollo final de novedades se encuentra en master.

**Sub Tareas**

- [x] Encontrar el código comentareado y revisar su funcionamiento.
- [x] Corregir el código correspondiente a la verificación de novedaedes poscontractuales desde certificaciones.
- [x] Probar la funcionalidad y documentar el issue.

**Criterios de aceptación**

- [x] Revisión de certificaciones contractuales y tratamiento de novedades CPS (deberían estar implementadas y comentareadas).
- [x] Ajustar el código encontrado para que muestre correctamente las novedades poscontractuales en las certificaciones contractuales.
- [x] Realizar pruebas de funcionamiento.
- [x] Documentar el issue con el ajuste realizado.

**Requerimientos**

- [x] Código comentareado de uso de novedades poscontractuales en el módulo de evaluación.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Master.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ludwinggsanchez** [comment]
Aparentemente el campo de novedades está limitado a los roles ASISTENTE_JURIDICA Y ORDENADOR_GASTO. Verificar.

**Comment by ludwinggsanchez** [comment]
Se habilitan las novedades en las certificaciones. Sin embargo, se debe confirmar cómo se afectan las fechas de inicio, fin y el valor del contrato. Se adjunta imagen de contrato que tuvo prórroga y la certificación muestra la fecha de terminación original del contrato.

![image](https://github.com/udistrital/evaluacion_cliente/assets/35748918/01ec8622-d222-4984-b363-83204faf9a15)

**Comment by milo19980525** [comment]
Respondiendo las inquietudes:

Se debería habilitar también para el rol de contratista.
Debería salir fecha fin contrato inicial y fecha adición y prorroga.

**Comment by ludwinggsanchez** [comment]
Resolver:

- El plazo del contrato, valor del contrato, fechas de inicio y fin se deben modificar según las novedades.
- Las novedades incluidas en el contrato deben estar limitadas a quien fue incluido en ellas.

**Comment by ludwinggsanchez** [comment]
Pendiente agregar variable de entorno NOVEDADES_CRUD_URL

**Comment by milo19980525** [comment]
Solicitud Tuleap: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=56688&group_id=116

**Comment by ludwinggsanchez** [comment]
Se generan certificaciones contractuales diferenciadas para el cedente y el cesionario en contratos con esta particularidad

**Comment by milo19980525** [comment]
Revisar terminación anticipada, suspensión y reinicio.

**Comment by ludwinggsanchez** [comment]
Dado que el sistema requiere de la información del acta de inicio, se muestra alerta si no se encuentra.

![image](https://github.com/udistrital/evaluacion_cliente/assets/35748918/bebf7f81-4bcd-4417-b2ee-8082adbb7063)

**Comment by ludwinggsanchez** [comment]
Se implementa soporte a las novedades contractuales en módulo de certificacones contractuales con las siguientes observaciones:

- Se puede elegir si la observación de la novedad se incluirá en el documento, sin embargo, la información de la novedad afecta las fechas y la duración del contrato
- Las novedades se podrán incluir en el contrato únicamente si el proveedor para el que se está generando la certificación tenía el contrato al momento del registro de la misma.
- Se implementaron las novedades de cesión, adición/prórroga, suspensión y terminación anticipada.
- Se ajusta el header en todas las páginas de la certificación.

**Comment by milo19980525** [comment]
Terminación anticipada: 1566 - 2023
Suspensión: 998 - 2023
