### ISSUE TITLE
Gestion para despliegue de cliente de evaluaciones en test

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/evaluacion_cliente#26]
se requiere 
- [x] configurar path 
- [x] variables de entorno 

- [x]  archivos de integración continua 

- [x] resolución de problemas de compilación y despliegue 

- [x] registro de cliente en wso2 en test (incluye permisos sobre las apis
, de las que ya esten arriba en el instante de realizar la tarea)

- [x] validación de funcionamiento base

**Comment by BOTOOM** [comment]
se realiza la solicitud mediante kamban pero aun nos e informa al ingeniero

https://tuleap.udistrital.edu.co/plugins/tracker/?aid=34266

**Comment by Eduargonzalez** [comment]
Por favor informar al ingeniero para que nos colabore con el tramite de dicha solicitud.

**Comment by BOTOOM** [comment]
el cliente ya fue desplegado hace falta el registro e wso2 y que tenga permisos sobre las respectivas apis
