### ISSUE TITLE
modulo de realizar evaluacion

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/evaluacion_cliente#28]
después de realizado lo correspondiente al issue #18 se requiere realizar lo siguiente: 

| ***los items se listaran en el orden en el cual se aconseja realizarlos*** |
| ----- |

- [x] el llenarse la evaluación se debe validar que todas las secciones han sido evaluadas. 

- [x] si por algún error el puntaje es menor a cero o mayor a cien mandar una alerta. 

- [x] construir en el cliente un servicio que conecte con el api de `evaluacion_crud` 

- [x] al llenar y validar la evaluación , se debe realizar un post al api crud, a la tabla `evaluacion` y la tabla `resultado_evaluacion`. Esto debe de ir con los datos respectivos que pide el api, debe de tenerse en cuenta que las fechas no se envían. 

- [x] después de realizar varias pruebas de ingreso, verificar con el api si se ingresaron con exito. 

- [x] al culminar los items anteriores, al momento de seleccionar el realizar una evaluación, primero deberá de realizarse una consulta para saber si ese proveedor con ese contrato y vigencia ya tenia previamente una evaluación realizada. 

- [x] si no se tenia ninguna evaluación realizada, se puede proceder de manera normal a pedir la plantilla y permitir realizar la evaluación. 

- [ ] si ya se tenia una evaluación realizada, se procede a realizar la petición de la plantilla según su ID, en este caso no se pide la ultima ya que esta puede ser una evaluación de una plantilla anterior, o en el caso del momento en el que se aplique reducer se podría verificar por el ID, para evitar la petición, pero por ahora, para el caso en el que ya exista una evaluación realizar la petición de la platilla. **(De acuerdo a la lógica que usé no es necesario hacer este paso)**

- [x] al culminar con el tiem anterior y tener la plantilla cargada se debe de cargar la evaluacion la cual ya fue previamente obtenida, al cargarla se deben de cargar los campos seleccionados y el puntaje final, todo debe estar diligenciado. 

- [x] si no se tenia evaluación se permitirá el post normal, pero si se cargo una evaluación ya existente y se edito, se realizara un post pero en este caso a la tabla de `resultado_evaluacion` , y al registro anterior de evaluación de le hará un put solo para pasar su estado de activo a false.

- [x] en adición al momento en el que exista una plantilla y se abra el componente de realizar evaluación (en este caso para actualizar la evaluación) deberá aparecer un modal diciéndole al usuario una advertencia como : "ya hay una evaluación existente, usted procederá a modificarla", con el fin de que el usuario tenga en cuanta que ya existe una evaluación previa.

---
 ***nota importante: el campo de item evaluado es opcional de llenarlo***

**Comment by grumysh** [comment]
Se ha intentado ingresar a la tabla  ResultadoEvaluación un registro pero no se ha tenido exito, primero porque un campo tenía mal el tipo de dato  y ahora no acepta el json de la evaluación se ha hecho una investigación de como se ingresa json mediante postgres pero no se ha tenido exito( https://www.postgresqltutorial.com/postgresql-json/)

**Comment by grumysh** [comment]
![Captura de pantalla de 2020-01-03 16-13-33](https://user-images.githubusercontent.com/29903400/71758461-f0885180-2e6d-11ea-98bb-8c12adfb1bbc.png)

Se ha realizado esta peticion de direfentes maneras, cambiando el json pero no sirve la petición.

**Comment by grumysh** [comment]
Estos días se han realizado prueba de como ingresar el json

Se ha ingresado un resultado evaluacion con la propiedad ResultadoEvaluación como "{}", y si ingresa. 
![Captura de pantalla de 2020-01-05 11-07-02](https://user-images.githubusercontent.com/29903400/71786068-81c60800-2fd5-11ea-884d-33e1bebd66b7.png)


Pero al ingresar una propiedad al json no sirve :| 
![Captura de pantalla de 2020-01-05 11-15-40](https://user-images.githubusercontent.com/29903400/71786176-b8e8e900-2fd6-11ea-8971-8b4b1d5b6f6f.png)

**Comment by grumysh** [comment]
Pero si se envía el json así si ingresa:

![Captura de pantalla de 2020-01-05 11-15-10](https://user-images.githubusercontent.com/29903400/71786290-d074a180-2fd7-11ea-9d32-af0d3be80e57.png)

**Comment by grumysh** [comment]
Despues de varias pruebas, el json se logra ingresar a la base de datos desde postman

![Esta si es](https://user-images.githubusercontent.com/29903400/71786447-5b09d080-2fd9-11ea-91d9-decafb58bb09.png)

**Comment by grumysh** [comment]
Se guarda el resultado de la evaluación
![guardado](https://user-images.githubusercontent.com/29903400/71786896-1123e900-2fdf-11ea-84b6-dbca9d3981be.png)

**Comment by grumysh** [comment]
Se realizan pruebas para comprobar que si es están guardando bien las evaluaciones:
![prueba](https://user-images.githubusercontent.com/29903400/71787054-a5db1680-2fe0-11ea-9142-33cc81bcc321.png)

**Comment by grumysh** [comment]
Tareas pendientes: 
- [x] Implementar put para poner en Activo:False el resultado de la evaluación pasada y el post para subir un nuevo resultado_evaluación.

- [x] Poner mensaje de alerta cuando se va a editar una evaluación.

- [x] Revisar porque se está cargando la plantilla llena.

- [x] Guardar el label de item a evaluar.

**Comment by anlramirezs11** [comment]
Al revisar el porque se está cargando la plantilla llena con la califiación de la ultima evaluación, se llega a conclusión de que el problema es de lo implementado en #40. @BOTOOM 

Esto se confirma porque al cambiar el cargue de la plantilla  (traerlo directamente del mid) ese bug no pasa.
![image](https://user-images.githubusercontent.com/29903400/71918738-ee194680-3150-11ea-85e6-541da850d1be.png)
