### ISSUE TITLE
modulo de ver evaluacion

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/evaluacion_cliente#29]
con el fin de poder visualizar de las evaluaciones realizadas se requiere un modulo en el cual contemplen los siguientes ítems.

| ***se aconseja seguir en el siguiente orden , no es obligatorio el orden, pero si aconsejable*** |
| ---- |

- [x] en el filtro al momento de dar clic al boton de ver evaluación deberá verificar si ya había una evaluación o no 

- [x] si no había previamente una evaluación , se debe de mostrar un Modal y devolver al usuario al filtro. 

- [x] si ya existía previamente una evaluación esta sebe ser cargada en el modulo de panilla dinámica junto a su plantilla respectiva .(se aclara que el modulo de plantilla esta contenido en el componente de ver evaluación) 

- [x] siguiendo el mockup se debe de traer el contrato con su vigencia respectiva y su proveedor, estos se traen de Argo. 

- [x] con los datos traídos del contrato y con el resultado de la evaluación se deben de cargar los campos respectivos en el mockup diferentes a la plantilla de evaluación. 

- [x] de debe de dejar flotante o fuera de los div contenidos de la evaluación , este boton sera el boton parra imprimir evaluación.

**Comment by grumysh** [comment]
Ya se pueden visualizar evaluaciones.
![ver evaluacion](https://user-images.githubusercontent.com/29903400/71843113-278a7d00-3091-11ea-815d-c9a248ddc2f0.png)

**Comment by grumysh** [comment]
Si no tiene evaluaciones se muestra un modal informando que no hay evaluación

![no tiene evaluacion](https://user-images.githubusercontent.com/29903400/71847017-f2cef380-3099-11ea-867c-d0c60a8f3861.png)

**Comment by grumysh** [comment]
![ver evaluación](https://user-images.githubusercontent.com/29903400/72110390-20b87000-3306-11ea-8ab9-2c44e307b7ff.png)

Vista implementada.
