### ISSUE TITLE
Implementación de paleta de colores en el cliente

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/evaluacion_cliente#5]
según la paleta de colores del issue udistrital/evaluacion_cliente_depressed#5 implementarla en el cliente , teniendo en cuenta, los menus, footer, navbar y demás elementos de la interfaz.

adicionalmente se debe de conseguir el logo de ágora y colocarlo

**Comment by BrayanB24** [comment]
Se queda a la espera que la diseñadora envíe los archivos y los códigos hexadecimal de los colores que corresponden al sistema de AGORA.
