### ISSUE TITLE
Realizar manual de usuario para Agora

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/evaluacion_cliente#63]

**Comment by grumysh** [comment]
[Link manual de usuario](https://drive.google.com/open?id=1lNElZ34dYF3W2UIqUTzsP8YcpV23YdVi)

**Comment by grumysh** [comment]
[V1 Manual de Usuario - Agora](https://github.com/udistrital/evaluacion_cliente/files/4156076/V1.Manual.de.Usuario.-.Agora.docx.pdf)

**Comment by grumysh** [comment]
Versión del manual de usuario teniendo en cuenta sugerencias de @Eduargonzalez 
[V1 Manual de Usuario - Agora.pdf](https://github.com/udistrital/evaluacion_cliente/files/4161110/V1.Manual.de.Usuario.-.Agora.pdf)
