### ISSUE TITLE
crear las rutas (componentes vacíos)

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/evaluacion_cliente#7]
de a cuerdo a los mockup de del cliente es necesario crear rutas por cada vista que alli se plantea de cada submodulo,adicionalmente crea una ruta con su componente vacios para la vista de administración de plantillas

**Comment by BrayanB24** [comment]
Se añaden las rutas vacías con sus módulos y componentes vacíos, se hace prueba de cada uno de estos y quedan funcionando de manera correcta. Se da por terminada la tarea.
