### ISSUE TITLE
Creación de Mockups para nueva funcionalidad de ver y descargar certificaciones

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/evaluacion_cliente#72]
Realizar mockups que permitan observa las vistas tanto del supervisor como del proveedor para ver los certificados generados por la evaluación de proveedores.

**Comment by ddguerra90** [comment]
Los mockups fueron aprobados por el lider tecnico y el lider del proyecto

**Comment by FrederickUdis** [comment]
se realizaron los respectivos mockups, se le mostraron al respectivo lider 
![image](https://user-images.githubusercontent.com/30853509/103103490-65104f00-45ef-11eb-8b6f-dce49fb0ce9f.png)
