### ISSUE TITLE
Creación de vistas para Administrador y proveedor/contratista

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/evaluacion_cliente#73]
Creación de vistas para usuarios de tipo Administrador y Contratista/Proveedor

- [x] Crear componentes para vista de Supervisor
- [x] Crear componentes para vista de Contratista/proveedor
- [x] Crear menu lateral de Certificaciones

**Comment by FrederickUdis** [comment]
se crearon dos vistas de certificaciones.

![image](https://user-images.githubusercontent.com/30853509/103103564-d5b76b80-45ef-11eb-8a6a-286ad97d8e11.png)
la prima como administrador, esta vista contiene el filtro del administrador la cual permite realizar búsquedas por numero de identificación, numero de contrato y vigencia.

la segunda vista es la vista de certificaciones-contratista, la cual solo permite buscar los contratos asociados al usuario que ingreso a la plataforma.

![image](https://user-images.githubusercontent.com/30853509/103103624-51191d00-45f0-11eb-8c4a-9844ccbb5f30.png)

**Comment by FrederickUdis** [comment]
además se creo el botón del menú lateral "certificaciones" con la herramienta 
https://pruebasconfiguracion.portaloas.udistrital.edu.co/ 
![image](https://user-images.githubusercontent.com/30853509/103103652-832a7f00-45f0-11eb-8ab2-1ded511618fa.png)

**Comment by FrederickUdis** [comment]
se habilito el filtro de búsqueda de los roles correspondientes con sus respectivos botones.
el rol de administrador tiene dos botones los cuales son de crear certificaciones y mostrar certificación.
![image](https://user-images.githubusercontent.com/30853509/103103693-cedd2880-45f0-11eb-883b-3055e34e36fc.png)

el rol de contratista y proveedor solo tiene un botón el cual le permite ver las certificaciones propias para descargarlas 
![image](https://user-images.githubusercontent.com/30853509/103103755-5d51aa00-45f1-11eb-800d-249a265519b1.png)
