### ISSUE TITLE
Creación de mockups para nuevas vistas

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/evaluacion_cliente#74]
Para las nuevas vistas a desarrollar ir mostrando los mockups para su aprobación

**Comment by FrederickUdis** [comment]
se crearon los respetivos mockups para las vistas de contratistas, proveedor y administrador para las certificaciones.
Se utilizo la herramienta diagrams la cual esta en el siguiente link
https://app.diagrams.net/

**Comment by FrederickUdis** [comment]
En  la creación de cada vista ser utilizo una vista vista base como se muestra en la siguiente imagen.
![image](https://user-images.githubusercontent.com/30853509/103553295-40cc3200-4e7b-11eb-9f1a-e6289de6b770.png)

**Comment by FrederickUdis** [comment]
vista del filtro del administrador 
![image](https://user-images.githubusercontent.com/30853509/103557636-7c69fa80-4e81-11eb-921c-360d26f82c57.png)

**Comment by FrederickUdis** [comment]
vista de de la tabla del resultado del administrador 
![image](https://user-images.githubusercontent.com/30853509/103557781-b4713d80-4e81-11eb-9491-ae6fc9204bc6.png)

**Comment by FrederickUdis** [comment]
vista del listado de certificación con el rol de administrador
![image](https://user-images.githubusercontent.com/30853509/103557916-e2ef1880-4e81-11eb-884f-04a8f2925bde.png)

**Comment by FrederickUdis** [comment]
Vista del modulo de creación de certificación del rol de administrador. 
![image](https://user-images.githubusercontent.com/30853509/103557975-f69a7f00-4e81-11eb-914d-70f1b7562f1c.png)

**Comment by FrederickUdis** [comment]
Vista del modulo de certificaciones del rol del contratista
![image](https://user-images.githubusercontent.com/30853509/103558073-1d58b580-4e82-11eb-82f7-db0a7f018970.png)

**Comment by FrederickUdis** [comment]
archivo en pdf donde muestra todas las vistas con su descripción.
[VistaCertificaciones-modulo-creacion y descarga.pdf](https://github.com/udistrital/evaluacion_cliente/files/5765794/VistaCertificaciones-modulo-creacion.y.descarga.pdf)
