### ISSUE TITLE
Creacion de pdf para generar certificacion

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/evaluacion_cliente#75]
Definir la libreria a utilizar para construir las certificaciones segun los modelos ya suministrados

**Comment by FrederickUdis** [comment]
se creo el  componente crear_certificacion para la generación de la certificación en pdf 
![image](https://user-images.githubusercontent.com/30853509/103550617-2d1ecc80-4e77-11eb-8dcf-03deaebe03de.png)
este modulo cuenta con todas las funciones de la creación de la certificación además de la generación de la certificación en pdf.

**Comment by FrederickUdis** [comment]
En la creación del pdf se va a utilizar pdfmaker con la herramienta Pdfmake-wrapper la cual cuenta con la siguiente documentación. 
https://www.npmjs.com/package/pdfmake-wrapper

**Comment by FrederickUdis** [comment]
Para la instalación de la librería se debe utilizar npm con la siguiente linea de comandos 
npm install pdfmake --save

En la implementación es fundamental importar todos los componentes de Pdfmake-wrapper como se muestra en la linea de código y en la imagen

import { PdfMakeWrapper } from 'pdfmake-wrapper';

![image](https://user-images.githubusercontent.com/30853509/103551185-fc8b6280-4e77-11eb-9a46-3245f27f6b48.png)

**Comment by FrederickUdis** [comment]
**Problema**
![image](https://user-images.githubusercontent.com/30853509/103681789-ebb11e80-4f55-11eb-95e2-6855158b30f8.png)
fuentes no encontradas en pdfmaker ademas del formato

**Comment by FrederickUdis** [comment]
se creo una Reunión con el ingeniero jhon el cual nos menciona que la mejor opción para subir los pdf a nuxeo es utilizar los métodos utilizado por los demás sistemas

**Comment by FrederickUdis** [comment]
los métodos mencionados son los siguientes.

![image](https://user-images.githubusercontent.com/30853509/104495611-f8f98900-55a5-11eb-886c-22fb6ca676d5.png)

![image](https://user-images.githubusercontent.com/30853509/104495675-0e6eb300-55a6-11eb-8d09-b06fde8c5c70.png)

**Comment by FrederickUdis** [comment]
se obtiene la información del endpoint 
![image](https://user-images.githubusercontent.com/30853509/104644317-9c689d80-567b-11eb-83ab-44bce8b26756.png)
Al realizar la petición Get Obtenemos todos los datos del contrato

El método utilizado para la obtención es el siguiente. 
![image](https://user-images.githubusercontent.com/30853509/104644399-ba360280-567b-11eb-8942-feb20eefe312.png)

**Comment by FrederickUdis** [comment]
Para solucionar el problema de los estilos de letras de opto por usar pdfmake-font-generator la cual es una herramienta que permite utilizar diferentes estilos de letras.

**Comment by FrederickUdis** [comment]
para utilizar pdfmake-font-generator se su la siguiente documentacion: 
**https://github.com/Lugriz/pdfmake-font-generator**
Donde se explica claramenta como hacer para importar diferentes estilos a un archivo js, en nuestro caso la fueste utilizada fue Calibri Light (Títulos) Numero 14 para los titulos y numero 11 para el cuerpo del documento.
las fuentes fueron obtenidas de https://www.onlinewebfonts.com/download/8922aedb2c18008da7daf4f93fd60bdc
el cual es un portal que permite descargar he importar diferentes estilos de fuentes.

**Comment by FrederickUdis** [comment]
el archvio js tiene el nombre de custom-fonts.js y esta en la ruta \evaluacion_cliente\src\assets\skins\lightgray\fonts\custom-fonts.js
este archivo fue creado con la documentación del pdfmake-font-generator y solo necesita importarse como se muestra en la siguiente imagen.
![image](https://user-images.githubusercontent.com/30853509/104996970-d4af0980-59f6-11eb-8926-d8b1aad6d70a.png)
 Para implementarlo porfavor revisar la documentación de pdfmaker

**Comment by FrederickUdis** [comment]
Otra forma de utilizar diferentes estilos es con el link del estilo en formato .ttf como se muestra en la siguiente imagen 
![image](https://user-images.githubusercontent.com/30853509/104997114-0a53f280-59f7-11eb-93c5-18f7518e0337.png)
y importarlo en el método de estilos del pdfmaker-wrapper como se muestra en la siguiente imagen.
![image](https://user-images.githubusercontent.com/30853509/104997218-3a02fa80-59f7-11eb-8afb-f246b08e506a.png)

**Comment by FrederickUdis** [comment]
**CERTIFICACIONES OPS**

se crea la certificaciones de ops de la misma forma de cps pero con sus respectivos cambios como se muestra en la siguiente imagen se utiliza pdfmaker y pdfmaker-wrapper 
![image](https://user-images.githubusercontent.com/30853509/107103137-8cf7f280-67ea-11eb-8507-f6377a7f16f5.png)

**Comment by FrederickUdis** [comment]
se asigna cada lugar en nuxeo para guardar los dos tipos de certificaciones las de cps y ops

**Comment by FrederickUdis** [comment]
**FUENTES**
se presento un problema al utilizar una url para obtener las fuentes por este motivo fue necesario obtener las fuentes y agregar las al proyecto en forma de un archivo.tff
de esta forma de optimizaron las peticiones http y se obtiene el pdf de forma rapida

**Comment by FrederickUdis** [comment]
**### **IMAGENES Y CUERPO DEL DOCUMENTO****

Para el manejo de las imágenes se implementaron dos formas, la primera fue la creación de una función asíncrona la cual crea un objeto tipo IMG (IMG hace parte de la librería pdfmake-wrapper)  como se muestra en la siguiente imagen. 
![image](https://user-images.githubusercontent.com/30853509/107104238-bd419000-67ee-11eb-8b13-0e13762782ec.png)

la segunda forma se utilizo para añadir la firma en la certificación cps y fue utilizando la librería pdfmake la cual permite agregar imágenes al pdf pero las imágenes deben estar en base 64 como se muestra en la siguiente imagen. 
![image](https://user-images.githubusercontent.com/30853509/107104295-faa61d80-67ee-11eb-95b1-e906c231b549.png)
para añadir la imagen se utilizo el método PDF.ADD() de la librería  pdfmake-wrapper y se implementa como en la siguiente imagen.
![image](https://user-images.githubusercontent.com/30853509/107104348-3e008c00-67ef-11eb-9fc4-141f5a3cfced.png)
**docDefinition** hace parte de una estructura para crear el cuerpo del documento el cual contiene la mayoría de información que va dentro del pdf y se crea como se muestra en la siguiente imagen.
![image](https://user-images.githubusercontent.com/30853509/107104391-74d6a200-67ef-11eb-97dd-f5b3ace4034b.png)

**Comment by FrederickUdis** [comment]
**INFORMACION DE LAS CERTIFICACIONES**
Para obtener todos los datos de las certificaciones se utilizaron las siguientes variables de entorno.
![image](https://user-images.githubusercontent.com/30853509/107104487-d860cf80-67ef-11eb-90af-75bf6966fbc9.png)

se realizo un get para obtener los datos del contrato como se muestra en la siguiente imagen 
![image](https://user-images.githubusercontent.com/30853509/107104510-faf2e880-67ef-11eb-9f31-b312f000e958.png)

**Comment by FrederickUdis** [comment]
Se cambian las imágenes en formato base 64 como se muestran en las siguientes imágenes.
![image](https://user-images.githubusercontent.com/30853509/107991328-63865600-6fa4-11eb-8bce-407e120f265c.png)
La imagen 1 representa la firma de la certificación.

 
![image](https://user-images.githubusercontent.com/30853509/107991391-87e23280-6fa4-11eb-911f-0bc18b9b0e11.png)
La imagen 2 representa el escudo que va en la parte superior derecha del documento

**Comment by FrederickUdis** [comment]
Se añade un hash para validar autenticación del documento

**Comment by FrederickUdis** [comment]
**Certificaciones OPS**
De la misma forma como se crearon las certificaciones cps se crearon las ops
