### ISSUE TITLE
Carga de documentos en el gestor documental NUXEO

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/evaluacion_cliente#79]
Realizar la carga de las certificaciones generadas en el sistema de nuxeo.

**Comment by FrederickUdis** [comment]
se logra cargar los datos de pdf a nuxeo con el siguiente método
![image](https://user-images.githubusercontent.com/30853509/104480447-93e86800-5592-11eb-98a4-ea3e69fc1f3b.png)

**Comment by FrederickUdis** [comment]
se habla con el ingeniero jhon y se menciona que se debe convertir los pdf a blod para cargarlos a nuxeo como se muestra en la siguiente imagen 
![image](https://user-images.githubusercontent.com/30853509/104480609-c2664300-5592-11eb-8678-638f32a0e111.png)

**Comment by FrederickUdis** [comment]
Para obtener los documentos de nuxeo se utilizaron los métodos de nuxeo service , ademas se creo un metodo el cual solo trae un documento de nuxeo
![image](https://user-images.githubusercontent.com/30853509/107102975-06dbac00-67ea-11eb-813d-7a41326c240d.png)

![image](https://user-images.githubusercontent.com/30853509/107103003-1f4bc680-67ea-11eb-9e65-a47066f0f7c6.png)
cabe resaltar que el método traer un blob y se muestra en una nueva ventana con
![image](https://user-images.githubusercontent.com/30853509/107103049-46a29380-67ea-11eb-9677-041c15736e22.png)
