### ISSUE TITLE
Solución de errores para despliegue del cliente

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/evaluacion_cliente#81]
Solucionar los errores pertinentes para probar el sistema en pruebas y posteriormente hacer el despliegue en producción.

- [x] Quitar la petición que colapsa el api de configuración (menús)
- [x] Revisar el correcto funcionamiento de todas las variables de entorno usadas por el cliente
- [x] Revisar que se este compilando el archivo de configuración para cada entorno

**Comment by FrederickUdis** [comment]
se Elimina la petición del api configuración la cual dañaba el menú.
La petición se encontró en : 
src\app\@core\utils\notificaciones.service.ts

![image](https://user-images.githubusercontent.com/30853509/106179504-082a2a80-6193-11eb-8aa8-2876fe6ad8b2.png)

y se elimino la petición queryNotification() como se muestra en la siguiente imagen donde se ve el comentario
![image](https://user-images.githubusercontent.com/30853509/106179724-56d7c480-6193-11eb-86c0-9d411dc6bcc7.png)

**Comment by FrederickUdis** [comment]
se reviso cada uno de los endpoint de los diferentes ambientes como se muestra en la siguiente imagen. 

![image](https://user-images.githubusercontent.com/30853509/106300488-900c4500-6224-11eb-8f56-92f74ab8ce8d.png)

![image](https://user-images.githubusercontent.com/30853509/106300530-9ac6da00-6224-11eb-8962-3b4c6b672e7f.png)

![image](https://user-images.githubusercontent.com/30853509/106300570-a914f600-6224-11eb-9855-3e69322e0547.png)

![image](https://user-images.githubusercontent.com/30853509/106300605-b4682180-6224-11eb-8673-a2441a694f6f.png)

**Comment by FrederickUdis** [comment]
Se hizo el push respectivo a la rama develop y mersh a la rama release.
La integración continua fue todo un éxito

**Comment by FrederickUdis** [comment]
se validan funcionalidades del modulo de evaluaciones en: 
https://pruebasevaluacion.portaloas.udistrital.edu.co/#/pages/dashboard
