### ISSUE TITLE
Tareas Faltantes

### ISSUE THREAD

**Issue by Eduargonzalez** [udistrital/evaluacion_cliente#96]
En reunión con el usuario el día 25 de febrero se presento el módulo de certificaciones de cumplimiento en un 95% de sus funcionalidades ya desarrolladas. El usuario solicitó ciertos ajustes los cuales se van a abordar en esta fase de desarrollo. 
A continuación se van a listar esos ajustes y faltantes que se evidenciaron en la presentación del módulo.

**Rol de asistente de sección de compras :** 

- [x] Validar si tiene evaluación y en dado caso que no debe permitir que el asistente de sección de compras ingrese dicha calificación basado en la documentación de dicho proveedor. Esto con el fin que el proceso no se vea afectado por la carencia de la información.
- [x] Separar la novedad de otro si, y dejar de la siguiente manera : Novedad de adición ( sólo se puede adicionar hasta el 50% del valor total del contrato.), Novedad de prórroga =  adición de tiempo en días y en meses.
- [x] Incluir firma y nombre del jefe de dependencia de sección de compras. (Pendiente información enviada por usuario).
- [x] Modificar el titulo de "Nuevas novedades" por "Novedades".
- [x] Poder eliminar una certificación ya creada.
- [x] Agregar fecha de creación/expedición en el formato.

**Rol del proveedor:**

- [x] Apenas ingresa el usuario debe mostrar los contratos que tiene o ha tenido.
- [x] Descargar certificaciones contractuales y también certificaciones de cumplimiento.

**Rol del asistente de Jurídica:**

- [x] Las actividades colocarlas en mayúscula. Ajustar formato de mostrar las novedades ( Jhon ) 
- [x] Poder eliminar una certificación ya creada.
- [x] Agregar fecha de creación/expedición en el formato al final del documento.

**Rol del contratista:**

- [x] Apenas ingresa el usuario debe mostrar los contratos que tiene o ha tenido.

**Ajustes trasversales:**

- [x] Modificar el subtitulo de las novedades omitiendo "novedad" Ej :  Novedad de suspensión cambiar a solo "suspensión".
- [x] Para incluir una novedad de cesión el usuario solo debe seleccionar dicha novedad mas no agregar texto.
- [x] Al seleccionar una novedad no debe incluir ningún titulo. ( se evidencio en el rol de asistente de sección de compras con la novedad de cesión)
- [x] La duración deben ir en letra y en numero. Ej : cinco (5) meses.
- [x] Los montos de dinero deben ir en letra y numero. incluir puntuación de miles.
- [x] Incluir en la duración la unidad de medida del tiempo en este caso meses.
- [x] Cuando se una persona jurídica (orden de compras, orden de servicio en este caso) mencionarla como "Empresa" https://drive.google.com/drive/u/0/folders/1Kx-E6iCRnAB-yqamDC-_QWOlIX5Xqydt
- [x] Validar que no se pueda agregar valores negativos. 
- [x] Validar que se puedan ingresar los formatos deseados de números.
- [ ] definir acceso al sistema ( certificaciones contractuales = cumplidos y certificaciones de cumplimiento = Ágora , Asistente de jurídica = Ágora y asistente de sección de compras = Ágora ) Definir esa parte con Jhon.

Nota: se listaron los ajustes evidenciados el día de ayer. tener en cuenta las otras generalidades del módulo mencionadas en anteriores sprint.

Acta de reunión: https://docs.google.com/document/d/18e0vjkFD-usOGG_bU7m6kVQPl_NYdw7a8RftBP-BKtI/edit#
Audio de reunión equipo : https://drive.google.com/file/d/1ighTUcENzcZGQzWEq9_G0pQKR6x-1fqJ/view

**Comment by FrederickUdis** [comment]
**Creación de botón de evaluación rol compras**
Se agrega el botón donde el usuario puede ingresar la nota de la evaluación si el usuario no ha realizado una evaluación como se muestra en la siguiente imagen.
![image](https://user-images.githubusercontent.com/30853509/109549603-2fc72800-7a9c-11eb-91af-2b5a536f4294.png)
De la misma forma se agrega un letra de advertencia que dice que el usuario no tiene una evaluación asociada y por este motivo se habilita este botón
![image](https://user-images.githubusercontent.com/30853509/109549700-51c0aa80-7a9c-11eb-8b6a-505781a97a74.png)

**Comment by FrederickUdis** [comment]
Se se paran las novedades de otro en novedades de **Adicción** y **Prorroga** como se muestra en la siguiente imagen 
![image](https://user-images.githubusercontent.com/30853509/109667987-b46a8280-7b3e-11eb-8ca9-899c500acc0b.png)

De la misma forma se valida que el valor de la adicción no supere el 50% del valor total del contrato y se muestra una alerta como lo muestra la siguiente imagen.

![image](https://user-images.githubusercontent.com/30853509/109668361-1a570a00-7b3f-11eb-864e-607e93858980.png)

**Comment by FrederickUdis** [comment]
Se añade formato de adicción y prorroga 
**Adicción**
![image](https://user-images.githubusercontent.com/30853509/109668984-ac5f1280-7b3f-11eb-9a30-fc5a2f3dbed4.png)

**Prorroga**
![image](https://user-images.githubusercontent.com/30853509/109669365-03fd7e00-7b40-11eb-886d-31896f8ae0e6.png)

**Comment by FrederickUdis** [comment]
Se añade la fecha y hora de creación del documento, como se muestra en la siguiente imagen.
![image](https://user-images.githubusercontent.com/30853509/109694616-03bdac80-7b59-11eb-911d-72e9c1ee089b.png)

**Comment by Eduargonzalez** [comment]
El msj de alerta al ingresar el monto de la adición presupuestal , tiene doble dd en adición. 

por favor corregir y colocar que no puede exceder el 50% del valor total del contrato.

**Comment by FrederickUdis** [comment]
**corrección mensaje.**
se ajusta mensaje.
![image](https://user-images.githubusercontent.com/30853509/109700031-48e4dd00-7b5f-11eb-868d-6afa73240b16.png)

**Comment by FrederickUdis** [comment]
**Rol de proveedor y contratista**
Se corrige error donde tenían acceso al filtro y crear certificaciones 
![image](https://user-images.githubusercontent.com/30853509/109865023-9467bb80-7c31-11eb-8196-daaad1cc45f2.png)
vista ejemplo rol contratista

**Comment by FrederickUdis** [comment]
**Funcionalidad Borrar**
se añade la funcionalidad borrar en los roles de administradores como se muestra en la siguiente imagen 
![image](https://user-images.githubusercontent.com/30853509/109902713-d2cc9d00-7c68-11eb-989f-7872436dc87f.png)

Para borrar se cambio el estado activo de true a false en el componente _evaluacion_cliente\src\app\components\ver-certificacion\ver-certificacion.component.ts_ y el proceso de eliminación se muestra en la siguiente imagen
![image](https://user-images.githubusercontent.com/30853509/109902776-eb3cb780-7c68-11eb-8fff-4f5acdcfdb1d.png)

**Comment by FrederickUdis** [comment]
**descargar certificaciones de cumplimiento y contractuales**
Se añade la funcionalidad para que el usuario con el rol de ops pueda descargar los dos tipos de certificaciones
![image](https://user-images.githubusercontent.com/30853509/110002996-f4b73580-7ce3-11eb-93a3-9b90115a909c.png)

**Comment by FrederickUdis** [comment]
**Conversión de numero a letras**
se implementa la conversión de cifras a letras como se muestra en la siguiente imagen.
![image](https://user-images.githubusercontent.com/30853509/110038420-bb93bb00-7d0d-11eb-87fe-be3decb077e2.png)

**Comment by FrederickUdis** [comment]
Se agrega la hora y fecha de creación al final del documento.
![image](https://user-images.githubusercontent.com/30853509/110336326-bfb42700-7ff2-11eb-9287-0dcb8e78c85a.png)
